sudo: false
jobs:
  include:
    - language: python
      python: 3.6
      install:
        - pip install flake8
        - pip install -r requirements.txt
      script:
        - flake8 --statistics --show-source --disable-noqa
        - nosetests

    - language: node_js
      node_js: 12
      install:
        - npm install
      script:
        - npm run build
        - npm run lint
